name: docmind-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - flask==2.3.3
    - PyMuPDF==1.23.8
    - gradio==4.0.0
    - sentence-transformers==2.2.2
    - faiss-cpu==1.7.4
    - groq==0.4.1
    - python-dotenv==1.0.0
